module.exports = {
  Asset: require('./src/Asset/Asset'),
  Candle: require('./src/Candle/Candle'),
  CandleSet: require('./src/CandleSet/CandleSet'),
  Epoch: require('./src/Epoch/Epoch'),
  Exchange: require('./src/Exchange/Exchange'),
  Instrument: require('./src/Instrument/Instrument'),
  KeyChain: require('./src/KeyChain/KeyChain'),
  Keys: require('./src/Keys/Keys'),
  Location: require('./src/Location/Location'),
  Market: require('./src/Market/Market'),
  Organization: require('./src/Organization/Organization'),
  Person: require('./src/Person/Person'),
  Persona: require('./src/Persona/Persona'),
  Ticker: require('./src/Ticker/Ticker'),
  Trade: require('./src/Trade/Trade'),
  ZCandle: require('./src/ZCandle/ZCandle'),
  ZTrade: require('./src/ZTrade/ZTrade'),
  logger: require('./src/logger'),
}
